// Agent details configuration (en)
// Used by main.js for modal content
export const agentDetailsEn = {
  'architect': { name: 'architect', desc: 'Architecture analysis expert. full mode: C4 modeling, ADR, risk assessment; quick mode: 3-step quick assessment. For new projects, first-time analysis, mature codebase incremental scan.' },
  'java-developer': { name: 'java-developer', desc: 'Java software development Agent. Responsible for feature development and bug fixes in Maven/Gradle projects including Spring Boot / Jakarta EE apps. Runs compilation + tests after every change.' },
  'python-developer': { name: 'python-developer', desc: 'Python software development Agent. Handles Django/Flask/FastAPI web frameworks, data processing scripts, and automation tools. Runs syntax checks + tests after every change.' },
  'go-developer': { name: 'go-developer', desc: 'Go software development Agent. Handles backend services, CLI tools, and concurrent systems for Go module projects. Runs compilation + tests (with -race detection) after every change.' },
  'rust-developer': { name: 'rust-developer', desc: 'Rust software development Agent. Handles systems programming, CLI tools, and high-performance concurrent services for Cargo projects. Runs compilation + tests (with clippy checks) after every change.' },
  'csharp-developer': { name: 'csharp-developer', desc: 'C# software development Agent. Handles .NET/C# web apps (ASP.NET Core), desktop apps, and server development. Runs compilation + tests after every change.' },
  'cpp-developer': { name: 'cpp-developer', desc: 'C/C++ software development Agent. Handles system libraries, embedded software, and high-performance computing modules for CMake/Makefile projects. Runs compilation + tests (0 error, 0 warning) after every change.' },
  'web-developer': { name: 'web-developer', desc: 'Web frontend development Agent. Handles HTML/CSS/JavaScript/TypeScript/React/Vue code. Suitable for web UI development, component library construction, and frontend performance optimization. Runs build + tests after every change.' },
  'mysql-dba': { name: 'mysql-dba', desc: 'MySQL database administration expert. Responsible for installation & configuration, performance tuning, backup & recovery, database security auditing, and high-availability/disaster recovery design.' },
  'oracle-dba': { name: 'oracle-dba', desc: 'Oracle database administration expert. Responsible for installation & configuration, performance tuning, backup & recovery, database security auditing, and high-availability/disaster recovery (RAC/Data Guard) design.' },
  'postgresql-dba': { name: 'postgresql-dba', desc: 'PostgreSQL database administration expert. Responsible for installation & configuration, performance tuning, backup & recovery, database security auditing, and high-availability/disaster recovery (streaming replication/logical replication/Patroni) design.' },
  'documenter': { name: 'documenter', desc: 'Documentation writing and maintenance expert. Responsible for generating and updating README, API docs, design docs, and usage guides. Ideal for syncing documentation after code changes.' },
  'security-expert': { name: 'security-expert', desc: 'Security audit expert. Enforces security audit after code completion. Covers OWASP Top 10, CWE, memory safety, and 16 security dimensions. Blocking reports have the highest priority.' },
  'code-reviewer': { name: 'code-reviewer', desc: 'Code review expert. Focuses on code correctness, security, performance, and maintainability. Suitable for code quality review, design review, and architecture compliance checks.' },
  'quality-inspector': { name: 'quality-inspector', desc: 'Full-chain quality inspector. Checks all sub-agent deliverables: architecture analysis completeness, code quality gates, security audit coverage, DBA compliance, and documentation coverage. Rejects any non-conforming delivery.' },
  'reflector': { name: 'reflector', desc: 'Retrospective analysis Agent. After task completion, reviews PuaSE\'s delegation chain — analyzing delegation decisions, identifying efficiency gaps, extracting improvement strategies, and writing recommendations to .PuaSE/improvement-track.md.' }
};
